package Analizer;

public enum TokenType {
    PROGRAM, VAR, BEGIN, END, IF, THEN, ELSE, WHILE, DO, INTEGER,
    PLUS, MINUS, MULTIPLY, DIVIDE, EQUAL,
    LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON, COLON, ASSIGN, COMMA,
    LESS_THAN, GREATER_THAN, PERIOD, NUMBER, IDENTIFIER, EOF,
    LESS_THAN_OR_EQUAL, GREATER_THAN_OR_EQUAL, STRING_LITERAL
   
}
