/*
 */
package View;

import Analizer.Token;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akilly Akungondo
 */
public class TableView extends javax.swing.JFrame {

     private DefaultTableModel tokenTableModel; // Declare tokenTableModel as an instance variable

    private javax.swing.JTable tokenTable;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JLabel elapsedTimeLabel;

    // Constructor
    public TableView(DefaultTableModel model, JLabel label) {
        initComponents();
        tokenTableModel = model; // Initialize tokenTableModel
        tokenTable = new JTable();
        tokenTable.setModel(model);
        jScrollPane1.setViewportView(tokenTable);
        elapsedTimeLabel = label;
    }
public void displayTokens(List<Token> tokens, long elapsedTime) {
    DefaultTableModel model = (DefaultTableModel) TokenTable.getModel();
    model.setRowCount(0);
    for (Token token : tokens) {
        model.addRow(new Object[]{token.getLexema(), token.getTokenClass(), token.getLinha()});
    }
    ElapsedTimeLabel.setText("Tempo de Complilacao: " + elapsedTime + " ms"); // Update the elapsed time label
}

    public void displayError(String message) {
        JOptionPane.showMessageDialog(this, message, "Lexical Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        AnalizadorLexicoLabel = new javax.swing.JLabel();
        voltarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TokenTable = new javax.swing.JTable();
        ElapsedTimeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        AnalizadorLexicoLabel.setBackground(new java.awt.Color(0, 0, 51));
        AnalizadorLexicoLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        AnalizadorLexicoLabel.setForeground(new java.awt.Color(255, 255, 255));
        AnalizadorLexicoLabel.setText("Analizador Lexico ");

        voltarBtn.setBackground(new java.awt.Color(51, 51, 51));
        voltarBtn.setFont(new java.awt.Font("Source Sans Pro Black", 0, 10)); // NOI18N
        voltarBtn.setForeground(new java.awt.Color(255, 255, 255));
        voltarBtn.setText("Voltar");
        voltarBtn.setToolTipText("");
        voltarBtn.setBorder(null);
        voltarBtn.setBorderPainted(false);
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        TokenTable.setBackground(new java.awt.Color(255, 255, 255));
        TokenTable.setForeground(new java.awt.Color(0, 0, 0));
        TokenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Token", "Linha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TokenTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TokenTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(TokenTable);
        if (TokenTable.getColumnModel().getColumnCount() > 0) {
            TokenTable.getColumnModel().getColumn(0).setHeaderValue("Lexema");
            TokenTable.getColumnModel().getColumn(1).setHeaderValue("Token");
            TokenTable.getColumnModel().getColumn(2).setHeaderValue("Linha");
        }
        TokenTable.getAccessibleContext().setAccessibleParent(TokenTable);

        ElapsedTimeLabel.setBackground(new java.awt.Color(0, 0, 51));
        ElapsedTimeLabel.setFont(new java.awt.Font("Source Sans Pro Black", 0, 12)); // NOI18N
        ElapsedTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
        ElapsedTimeLabel.setLabelFor(ElapsedTimeLabel);
        ElapsedTimeLabel.setText("Tempo de Compilacao: 0 ms");
        ElapsedTimeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ElapsedTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnalizadorLexicoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AnalizadorLexicoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ElapsedTimeLabel))
                .addGap(22, 22, 22))
        );

        ElapsedTimeLabel.getAccessibleContext().setAccessibleParent(ElapsedTimeLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        AnalizadorView analizadorview = new AnalizadorView();
        analizadorview.setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_voltarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DefaultTableModel tokenTableModel = new DefaultTableModel(); // Create DefaultTableModel
                JLabel elapsedTimeLabel = new JLabel(); // Create JLabel
                TableView tableView = new TableView(tokenTableModel, elapsedTimeLabel); // Pass DefaultTableModel and JLabel to TableView constructor
                tableView.setVisible(true); // Set TableView visible
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnalizadorLexicoLabel;
    private javax.swing.JLabel ElapsedTimeLabel;
    private javax.swing.JTable TokenTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
